// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDatTourDuLichOnline.Data;

#nullable disable

namespace WebDatTourDuLichOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"));

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("Diem");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TourId");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.DonDatTour", b =>
                {
                    b.Property<int>("DonDatTourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonDatTourId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonDatTourId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TourId");

                    b.ToTable("DonDatTour", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("KhachHangId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.LoaiTour", b =>
                {
                    b.Property<int>("LoaiTourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiTourId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("LoaiTourId");

                    b.ToTable("LoaiTour", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("NhanVienId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"));

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<int>("DonDatTourId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("DonDatTourId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<string>("ChinhSachHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DichVuBaoGom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DichVuKhongBaoGom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemKhoiHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNguoiLon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaTreEm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiTourId")
                        .HasColumnType("int");

                    b.Property<string>("MaTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoCho")
                        .HasColumnType("int");

                    b.Property<int>("SoChoConLai")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("TourId");

                    b.HasIndex("LoaiTourId");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.YeuCauTuVan", b =>
                {
                    b.Property<int>("YeuCauTuVanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YeuCauTuVanId"));

                    b.Property<int?>("DonDatTourId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kenh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YeuCauTuVanId");

                    b.HasIndex("DonDatTourId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TourId");

                    b.ToTable("YeuCauTuVan", (string)null);
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.DanhGia", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDatTourDuLichOnline.Models.Tour", "Tour")
                        .WithMany("DanhGias")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.DonDatTour", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.KhachHang", "KhachHang")
                        .WithMany("DonDatTours")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDatTourDuLichOnline.Models.Tour", "Tour")
                        .WithMany("DonDatTours")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.KhachHang", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("KhachHangs")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.NhanVien", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.ThanhToan", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.DonDatTour", "DonDatTour")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DonDatTourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatTour");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.Tour", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.LoaiTour", "LoaiTour")
                        .WithMany("Tours")
                        .HasForeignKey("LoaiTourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTour");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.YeuCauTuVan", b =>
                {
                    b.HasOne("WebDatTourDuLichOnline.Models.DonDatTour", "DonDatTour")
                        .WithMany()
                        .HasForeignKey("DonDatTourId");

                    b.HasOne("WebDatTourDuLichOnline.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("WebDatTourDuLichOnline.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.Navigation("DonDatTour");

                    b.Navigation("KhachHang");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.DonDatTour", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatTours");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.LoaiTour", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("WebDatTourDuLichOnline.Models.Tour", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatTours");
                });
#pragma warning restore 612, 618
        }
    }
}
